services:
  - type: web
    name: data-ingestion-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PORT
        sync: false